### ISSUE TITLE
Releases Published Anywhere?

### ISSUE THREAD

**Issue by bbrowning** [jboss-openshift/openshift-ping#14]
I'd like to consume releases of openshift-ping from WildFly Swarm. Are the alpha and beta releases published anywhere? I checked Maven Central as well as the JBoss Nexus and wasn't able to find anything.

**Comment by slaskawi** [comment]
The "upstream" repository has been moved here: https://github.com/jgroups-extras/jgroups-kubernetes

I've just performed a release: https://repository.jboss.org/nexus/content/repositories/public/org/jgroups/kubernetes/

**Comment by pfyod** [comment]
@slaskawi  @errantepiphany what about the activemq part? Cannot find any "upstream" repository / release.

**Comment by errantepiphany** [comment]
@pfyod Red Hat builds releases internally, but you can build it yourself (including the activemq part) easily with a tag: https://github.com/jboss-openshift/openshift-ping/tags
